import type { Metadata } from "next"; // Next.js의 Metadata 타입을 import
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // 전역 스타일시트 import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// 1. 공통 메타데이터 정의 (SEO 관련 설정)
export const metadata: Metadata = {
  title: "Create Next App", // 브라우저 탭 제목
  description: "Generated by create next app",
};
// 2. RootLayout 컴포넌트 정의
// Root Layout은 필수적으로 children을 props로 받습니다.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> {/* 3. 필수: <html> 태그 */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}> {/* 4. 필수: <body> 태그 */}
        {/* === 공통 UI 요소 시작 === */}

        {/* 5. 핵심: children을 렌더링합니다. */}
        {/* 현재 경로에 해당하는 page.tsx 내용이 여기에 들어갑니다. */}
        {children}
      </body>
    </html>
  );
}
